site_name: Jérome Lesaint
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: fr
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode.
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime
  

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.mark
  - attr_list
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - md_in_html
  - pymdownx.blocks.html

plugins:
  - literate-nav:
      nav_file: SUMMARY.md
  - search: {} # This is necessary as search in incl. dy defautl if no pulg-ins set up. But as soon you have one, adding search is necessary...
  - encryptcontent:
      password_inventory:
        secret: "jerome"

nav:
- Welcome: index.md
- How To: HowTo.md
- La GTA:
  - La GTA: GTA/0-gtaTotal.md
  - Etape 1 - Saint Gingolphe - Novel: GTA/1-gta.md
  - Etape 2 - Novel - La Chapelle d'abondance: GTA/2-gta.md
  - Etape 3 - La CHapelle d'abondance - Refuge de Chéséry: GTA/3-gta.md
  - Etape 4 - Chéséry - Refuge Golèse: GTA/4-gta.md
  - Etape 5 - Golèse - Gite Salvagny: GTA/5-gta.md
  - Etape 6 - Salvagny - Moede Anterne: GTA/6-gta.md
  - Etape 7 - Moede Anterne - Les Houches: GTA/7-gta.md
  - Etape 8 - Les Houches - Les Contamines: GTA/8-gta.md
  - Etape 9 - Les Contamines - Croix du bonhomme: GTA/9-gta.md
  - Etape 10 - Croix du bonhomme - Balme: GTA/10-gta.md
  - Etape 11 - Refuge de Balme - Rosuel: GTA/11-gta.md
  - Etape 12 - Rosuel - Tignes: GTA/12-gta.md
  - Etape 13 - Tignes - Entre-2-eaux: GTA/13-gta.md
  - Etape 14 - Entre-2-eaux - Arpont: GTA/14-gta.md
  - Etape 15 - Arpont - Aussois: GTA/15-gta.md
- Randos: Randos.md

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/lesaintjerome
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/jerome-lesaint-52813a5/

copyright: Copyright &copy; 2024 Jérome Lesaint
  